### PR TITLE
Improved render animation decisions

### PR DESCRIPTION
**Pull request by iangilman**
@aeschylus This definitely fixes the thumbnail issue described here: 

https://github.com/sul-dlss/iiifManifestLayouts/pull/101#issuecomment-163477210

...and possibly some of the others. Can you test and let me know what you find broken?

### CODE REVIEW

**Comment by aeschylus** [comment]
Testing now.

**Comment by aeschylus** [comment]
Okay. This solves the resizing and jumping around on mode change, but here are some captures of two other problems.

### Thumbs entering from below

When the thumbs are being lazily loaded on scroll, new thumbs are rising up from below, rather than being loaded in place. This is again probably a call to the enterImages or some such at the wrong point in the d3 cycle, or with the wrong settings.

thumbs from bottom

### Line breaks

Maybe this was fixed in a different branch, but it seems the line-breaks in book mode are still a problem. This may only be happening after they have been resized, although I don't think so.

line breaks

**Comment by iangilman** [comment]
@aeschylus Thanks again for the reports...I'll look into these issues.

**Comment by iangilman** [comment]
@aeschylus I'm unable to recreate the book mode issue (Mac Chrome) with the latest master; the pairs always stay together as I resize the window. Here is what I'm doing to test: 
- Launch http://localhost:4000/example/
- Switch to overview
- Switch to "paged" mode
- Resize the window slowly

Is there anything else you're doing besides that?

**Comment by iangilman** [comment]
@aeschylus I believe #114 fixes the "entering from below" issue here.

**Pull request merged**
