### PR TITLE
[In Progress]: Make filmstrip for detail layout

### PR DESCRIPTION
**Pull request by nein09**
This is a step toward the solution for https://github.com/sul-dlss/iiifManifestLayouts/issues/9

### CODE REVIEW

**Comment by iangilman** [comment]
I like Lines being a real object. 

What's the bug you introduced?

**Comment by nein09** [comment]
The bug is that left pages at the end of a line have their right pages on the next line, in the grid. It's probably a case that I took out erroneously; I'm working on it now.

**Comment by nein09** [comment]
My thinking is that by extracting Lines in this way, it sets me up to add a function that is something like addItemsAllOnOneLine() that makes a filmstrip.

**Comment by nein09** [comment]
Fixed- I wasn't calculating the line length correctly for a paged layout.

**Comment by nein09** [comment]
Closing because #94 has been merged into master; re-opening as a PR on master.

**Pull request closed without merging**
